name: Docker Image CI

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag based on branch
        id: prep
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Running on default branch, tag = 'latest'"
            echo "::set-output name=tag::latest"
          else
            BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9]/-/g')
            echo "Running on branch '${{ github.ref_name }}', tag = '$BRANCH_NAME'"
            echo "::set-output name=tag::$BRANCH_NAME"
          fi

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag Dockerfile:${{ steps.prep.outputs.tag }}

      - name: Push the Docker image
        run: docker push my-image-name:${{ steps.prep.outputs.tag }}
