name: Docker Image CI

on:
  push:
    branches:
      - main
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository_owner.lower }}/studenthacksolar:${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name }}
          cache-from: type=registry,ref=${{ github.repository_owner.lower }}/studenthacksolar:cache
          cache-to: type=inline

      - name: Image digest output
        run: echo "The image digest is ${{ steps.build-and-push.outputs.digest }}"
